### ISSUE TITLE
Make image quality configurable

### ISSUE THREAD

**Issue by drKnoxy** [disintegration/imaging#40]
`Encode` always compresses jpegs at 95%, it would be nice if this was configurable, or accessible from `Save`
https://github.com/disintegration/imaging/blob/master/helpers.go#L94

**Comment by disintegration** [comment]
Hi,
`Save` is meant to be a shortcut for a most basic usecase for each image format. That's why it doesn't take any of format-specific options like `Quality` (for JPEG) or `Compression` (for TIFF) or `NumColors`, `Quantizer`, `Drawer` (for GIF). I think that if you need these options it's better to use specific packages directly (e.g. `jpeg.Encode`), than incorporating all the options into `imaging.Save`.
